# Generated by Django 2.2.7 on 2019-11-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191129_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
