# Generated by Django 2.2.7 on 2019-11-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_restaurants_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='score',
        ),
    ]
